#pragma once

#include <string>

namespace miniant::Lang {

enum class Language {
    English,
    Russian,
};

// Every string that the application shows to the user, writes to the log or
// puts into the settings file as a comment.
//
// Keep this list and the table in Lang.cpp in sync: every identifier must have
// an English and a Russian text.
enum class Str {
    // Main window
    WindowTitle,
    StatusStarting,
    ButtonReinitialize,
    ButtonFileMenu,
    ButtonOptions,
    ButtonOpenLog,
    ButtonDiagnostics,
    ButtonAbout,
    ButtonExit,

    // Tray menu
    TrayToggleEnabled,
    TrayReinitialize,
    TrayLog,
    TrayDiagnostics,
    TrayStartWithWindows,
    TrayAbout,
    TrayExit,

    // Status line
    StatusDisabled,
    StatusNotActive,
    StatusDriverMinimum,
    StatusPeriodLocked,
    StatusMoreDevices,

    // Notifications (short on purpose: a balloon shows only a few words)
    NotifyTitle,
    NotifyAudioTitle,
    NotifyDeviceTitle,
    NotifyDeviceNotReady,
    NotifyDisabledNoDevice,
    NotifyUpdateAvailable,
    NotifyUpdateLatest,
    NotifyUpdateFailed,
    NotifyUpdateClick,
    NotifyReportFailed,
    NotifySettingsUnreadable,

    StatusSuspended,
    StatusActive,
    StreamDetails,
    UnknownDevice,
    FlowRender,
    FlowCapture,
    LogMutexFailed,
    LogTrayForeignEvent,
    LogAudioSettings,
    LogUnknownArgument,
    LogInstanceNoAnswer,
    LogSettingsUnreadable,
    LogSettingsBackup,
    LogComFailed,
    LogWindowFailed,
    LogSessionNotifications,
    LogInterfaceScale,
    LogTrayHidden,
    LogPriorityFailed,
    LogPowerThrottlingFailed,
    LogPowerThrottlingOff,
    LogPowerThrottlingUnavailable,
    LogSettingsWriteFailed,
    RestartNeededTitle,
    RestartNeededText,
    RestartNeededHint,
    RestartLaterHint,
    ErrRestartFailed,
    LogRestartFailed,
    OpRestarting,
    LogLanguageChanged,
    LogFileOff,
    LogFileMissing,
    LogUpdatesDisabled,
    LogUpdateRunning,
    LogReinitInvalid,
    LogResumeApply,
    LogHotkeyRegisterFailed,
    LogHotkeyParseFailed,
    LogAutostartOpenFailed,
    LogAutostartWriteFailed,
    LogUpdateLeftover,
    LogStopped,
    LogRepeated,
    LogLowLatencyStarted,
    LogPeriodLocked,
    LogDiagCollected,
    LogDiagEnumeratorReady,
    LogDiagEnumeratorMissing,
    LogDiagEndpoints,
    LogDiagReportBuilt,
    LogTrayCreateFailed,
    LogTrayConfigureFailed,
    LogWindowClassFailed,
    LogWindowCreateFailed,
    ErrUnhandledException,
    ErrUnhandledExceptionUnknown,

    ErrAudioEnumeratorFailed,
    ErrAudioNotificationsFailed,
    ErrNotInitialised,
    ErrLowLatency,
    ErrNoEndpoint,
    ErrStreamInvalid,
    ErrDefaultEndpointQuery,
    ErrDefaultDeviceChanged,
    ErrStreamNotRunning,
    ErrNoAudioClient3,
    ErrActivateClient,
    ErrMixFormat,
    ErrEnginePeriods,
    ErrEngineLocked,
    ErrInitStream,
    ErrStartStream,
    ErrUrlParse,
    ErrResponseTooLarge,

    ReasonResume,
    ReasonUnlock,
    CliReportWritten,
    ArgConfigNeedsPath,
    ArgLogLevelNeedsValue,
    ErrEmptyUrl,
    ErrNoUpdateRepository,
    ErrGithubUnreachable,
    ErrNoReleases,
    ErrRateLimit,
    ErrHttpStatus,
    ErrGithubParse,
    ErrGithubUnexpected,
    ErrNoReleaseVersion,
    ErrDeleteLeftover,
    DiagTitle,
    DiagRule,
    DiagVersion,
    DiagGenerated,
    DiagWindows,
    DiagScale,
    DiagExecutable,
    DiagSettings,
    DiagConfig,
    DiagEnumeratorError,
    DiagAudiosrvHint,
    DiagDevicesRender,
    DiagDevicesCapture,
    DiagNoDevices,
    DiagDefaultMark,
    DiagCommunicationMark,
    DiagDeviceId,
    DiagDriver,
    DiagFormat,
    DiagPeriods,
    DiagUnknown,
    DiagResult,
    DiagSmallBuffer,
    DiagNoGain,
    DiagNoAudioClient3,
    DiagNotesHeader,
    DiagNotes,
    DiagPeriodsNoClient3,
    DiagPeriodDefault,
    DiagPeriodMinimum,
    DiagPeriodFundamental,
    DiagPeriodMaximum,
    DiagNoAudioClient3Detail,
    DiagMixFormatFailed,
    DiagEnginePeriodsFailed,
    DiagActivateFailed,

    SettingsPrefix,
    CfgErrNotObject,
    CfgErrParse,
    CfgErrRead,
    CfgWarnString,
    CfgWarnBool,
    CfgWarnInteger,
    CfgWarnRange,
    CfgWarnUnknownKey,
    CfgWarnUnknownValue,

    // Command line help (one block per language)
    HelpText,

    // Dialogs
    AboutTitle,
    AboutText,
    AboutUsage,
    AboutConfig,
    AboutProject,
    AboutSettings,
    DiagnosticsWriteFailed,

    // Window and log: operations
    OpStarted,
    OpSettingsFile,
    OpSettingsCreated,
    OpCommentsRewritten,
    OpSettingsUpgraded,
    OpAlreadyRunning,
    OpApplied,
    OpLogOpened,
    OpDriverMinimum,
    OpEnabled,
    OpDisabled,
    OpDeviceChanged,
    OpDeviceNotReady,
    OpGaveUp,
    OpDiagnostics,
    OpDiagnosticsFailed,
    OpHotkeys,
    OpAutostart,
    OpUpdateChecking,
    OpExiting,
    OpTrayUnavailable,
    OpDiagHint,
    ValueOn,
    ValueOff,

    SettingsWindowTitle,
    SettingsSave,
    SettingsCancel,
    SettingsOpenFile,
    SettingsReload,
    SettingsInvalidValues,
    SettingsOpenFileFailed,
    SettingsReloadFailed,
    SettingsTabWindow,
    SettingsTabAudio,
    SettingsTabOther,
    SettingsHeaderApplication,
    SettingsHeaderTray,
    SettingsHeaderMenu,
    SettingsHeaderAudio,
    SettingsHeaderReinit,
    SettingsHeaderPerformance,
    SettingsHeaderHotkeys,
    SettingsHeaderUpdates,
    SettingsHeaderLog,
    SettingsLanguage,
    SettingsLanguageAuto,
    SettingsLanguageEnglish,
    SettingsLanguageRussian,
    SettingsStartWithWindows,
    SettingsStartMinimized,
    SettingsMinimizeToTray,
    SettingsCloseAction,
    SettingsCloseMinimize,
    SettingsCloseExit,
    SettingsSingleInstance,
    SettingsTrayEnabled,
    SettingsNotifyError,
    SettingsNotifyDeviceChange,
    SettingsNotifyStateChange,
    SettingsMenuStatus,
    SettingsEnabledOnStartup,
    SettingsDataFlow,
    SettingsFlowRender,
    SettingsFlowCapture,
    SettingsFlowBoth,
    SettingsPeriod,
    SettingsPeriodMinimum,
    SettingsPeriodFundamental,
    SettingsPeriodFixed,
    SettingsRequestedPeriod,
    SettingsAllowPeriodSnap,
    SettingsReinitDeviceChanged,
    SettingsReinitDeviceState,
    SettingsReinitDeviceAdded,
    SettingsReinitDeviceRemoved,
    SettingsReinitResume,
    SettingsReinitUnlock,
    SettingsReinitEnableWhenDisabled,
    SettingsReinitFailureTimeout,
    SettingsReinitDebounce,
    SettingsProcessPriority,
    SettingsPriorityNormal,
    SettingsPriorityBelowNormal,
    SettingsPriorityIdle,
    SettingsDisablePowerThrottling,
    SettingsHotkeysEnabled,
    SettingsHotkeyToggle,
    SettingsHotkeyReinitialize,
    SettingsCheckOnStartup,
    SettingsLogLevel,
    SettingsLogLevelOff,
    SettingsLogLevelError,
    SettingsLogLevelWarn,
    SettingsLogLevelInfo,
    SettingsLogLevelDebug,
    SettingsLogLevelTrace,
    SettingsLogFilePath,
    SettingsLogMaxFileSize,
    SettingsLogMaxFiles,

    // Settings file comments
    CfgFileHeader,
    CfgApplicationSection,
    CfgStartMinimizedToTray,
    CfgMinimizeToTray,
    CfgCloseButtonAction,
    CfgSingleInstance,
    CfgStartWithWindows,
    CfgLanguage,
    CfgTraySection,
    CfgTrayEnabled,
    CfgNotificationsSection,
    CfgNotifyOnError,
    CfgNotifyOnDeviceChange,
    CfgNotifyOnStateChange,
    CfgMenuSection,
    CfgMenuShowStatus,
    CfgMenuToggle,
    CfgMenuReinitialize,
    CfgMenuLog,
    CfgMenuDiagnostics,
    CfgMenuStartWithWindows,
    CfgMenuAbout,
    CfgMenuExit,
    CfgAudioSection,
    CfgEnabledOnStartup,
    CfgDataFlow,
    CfgPeriodSelection,
    CfgRequestedPeriodFrames,
    CfgAllowPeriodSnap,
    CfgReinitSection,
    CfgReinitDeviceChanged,
    CfgReinitDeviceState,
    CfgReinitDeviceAdded,
    CfgReinitDeviceRemoved,
    CfgReinitResume,
    CfgReinitUnlock,
    CfgReinitEnableWhenDisabled,
    CfgReinitFailureTimeout,
    CfgReinitDebounce,
    CfgPerformanceSection,
    CfgProcessPriority,
    CfgDisablePowerThrottling,
    CfgUpdatesSection,
    CfgUpdatesCheckOnStartup,
    CfgHotkeysSection,
    CfgHotkeysEnabled,
    CfgHotkeysToggle,
    CfgHotkeysReinitialize,
    CfgLoggingSection,
    CfgLoggingLevel,
    CfgLoggingFilePath,
    CfgLoggingMaxFileSize,
    CfgLoggingMaxFiles,

    Count,
};

// Language of the current session. "auto" means the language of Windows.
Language Detect();
Language FromCode(const std::string& code);
const char* Code(Language language);

void Set(Language language);
Language Current();

// Text in the current language.
const char* Utf8(Str id);
std::wstring Wide(Str id);

// A number with its noun in the current language: "1344 frames", and in
// Russian the noun agrees with the numeral ("1 фрейм", "2 фрейма", "5 фреймов").
std::string Frames(unsigned int count);
std::string Channels(unsigned int count);

// "7.00 ms" with the unit of the current language.
std::string Milliseconds(double value);

}
