#pragma once

#include <string>

namespace miniant::Lang {

enum class Language {
    English,
    Russian,
};

// Every string that the application shows to the user, writes to the log or
// puts into the settings file as a comment.
//
// Keep this list and the table in Lang.cpp in sync: every identifier must have
// an English and a Russian text.
enum class Str {
    // Main window
    WindowTitle,
    StatusStarting,
    ButtonReinitialize,
    ButtonSettings,
    ButtonLog,
    ButtonDiagnostics,
    ButtonHideToTray,
    ButtonExit,

    // Tray menu
    TrayToggleEnabled,
    TrayReinitialize,
    TraySettings,
    TrayLog,
    TrayDiagnostics,
    TrayStartWithWindows,
    TrayAbout,
    TrayExit,

    // Status line
    StatusDisabled,
    StatusNotActive,
    StatusDriverMinimum,
    StatusPeriodLocked,
    StatusMoreDevices,

    // Notifications (short on purpose: a balloon shows only a few words)
    NotifyTitle,
    NotifyAudioTitle,
    NotifyDeviceTitle,
    NotifyDeviceNotReady,
    NotifyDeviceNotReadyHelp,
    NotifyDisabledNoDevice,
    NotifyEnabled,
    NotifyDisabled,
    NotifyDeviceChanged,
    NotifyUpdateAvailable,
    NotifyUpdateLatest,
    NotifyUpdateFailed,
    NotifyUpdateClick,
    NotifyReportFailed,

    StatusSuspended,
    StatusActive,
    UnknownDevice,
    FlowRender,
    FlowCapture,
    LogBanner,
    LogUpstream,
    LogLanguage,
    LogMutexFailed,
    LogInstanceNoAnswer,
    LogSettingsUnreadable,
    LogComFailed,
    LogWindowFailed,
    LogSessionNotifications,
    LogTrayHidden,
    LogPriorityFailed,
    LogPowerThrottlingFailed,
    LogPowerThrottlingOff,
    LogPowerThrottlingUnavailable,
    LogSettingsSaved,
    LogSettingsWriteFailed,
    LogConsoleRestart,
    LogLanguageChanged,
    LogLogSnapshotFailed,
    LogUpdatesDisabled,
    LogUpdateRunning,
    LogRepository,
    LogReinitInvalid,
    LogApplyRetry,
    LogResumeApply,
    LogHotkeyRegisterFailed,
    LogHotkeyParseFailed,
    LogAutostartOpenFailed,
    LogAutostartWriteFailed,
    LogUpdateLeftover,
    LogStopped,
    LogLowLatencyFailed,
    LogDriverMinimum,
    LogLowLatencyStarted,
    LogPeriodLocked,
    LogDiagCollected,
    LogDiagEnumeratorReady,
    LogDiagEnumeratorMissing,
    LogDiagEndpoints,
    LogDiagReportBuilt,
    LogTrayCreateFailed,
    LogTrayConfigureFailed,
    LogWindowClassFailed,
    LogWindowCreateFailed,

    ErrAudioEnumeratorFailed,
    ErrAudioNotificationsFailed,
    ErrNotInitialised,
    ErrLowLatency,
    ErrNoEndpoint,
    ErrStreamInvalid,
    ErrDefaultEndpointQuery,
    ErrDefaultDeviceChanged,
    ErrStreamNotRunning,
    ErrOpenEndpoint,
    ErrEndpointTransient,
    ErrNoAudioClient3,
    ErrActivateClient,
    ErrMixFormat,
    ErrEnginePeriods,
    ErrEngineLocked,
    ErrInitStream,
    ErrStartStream,
    ErrUrlParse,
    ErrResponseTooLarge,

    ErrConsoleAttach,
    ReasonResume,
    ReasonUnlock,
    ConsoleReportWritten,
    ArgConfigNeedsPath,
    ArgLogLevelNeedsValue,
    ErrEmptyUrl,
    ErrNoUpdateRepository,
    ErrGithubUnreachable,
    ErrNoReleases,
    ErrRateLimit,
    ErrHttpStatus,
    ErrGithubParse,
    ErrGithubUnexpected,
    ErrNoReleaseVersion,
    ErrDeleteLeftover,
    DiagTitle,
    DiagRule,
    DiagVersion,
    DiagGenerated,
    DiagWindows,
    DiagExecutable,
    DiagSettings,
    DiagConfig,
    DiagEnumeratorError,
    DiagAudiosrvHint,
    DiagFlowHeader,
    DiagNoDevices,
    DiagDefaultMark,
    DiagDeviceId,
    DiagDriver,
    DiagFormat,
    DiagPeriods,
    DiagUnknown,
    DiagResult,
    DiagSmallBuffer,
    DiagNoGain,
    DiagNoAudioClient3,
    DiagSummaryHeader,
    DiagSummary,
    DiagFlowRender,
    DiagFlowCapture,
    DiagPeriodsNoClient3,
    DiagPeriodsDetail,
    DiagNoAudioClient3Detail,
    DiagMixFormatFailed,
    DiagEnginePeriodsFailed,
    DiagActivateFailed,

    SettingsPrefix,

    // Command line help (one block per language)
    HelpText,

    // Dialogs
    AboutTitle,
    AboutText,
    DiagnosticsWriteFailed,

    // Console / log: operations
    OpStarted,
    OpSettingsFile,
    OpSettingsCreated,
    OpSettingsReloaded,
    OpAlreadyRunning,
    OpApplying,
    OpApplied,
    OpApplyFailed,
    OpEnabled,
    OpDisabled,
    OpReinitialising,
    OpDeviceChanged,
    OpDeviceNotReady,
    OpRetry,
    OpGaveUp,
    OpDiagnostics,
    OpDiagnosticsFailed,
    OpHotkeys,
    OpAutostart,
    OpUpdateChecking,
    OpExiting,
    OpTrayUnavailable,
    OpSessionNotificationFailed,
    OpReportHint,
    ValueOn,
    ValueOff,

    // Settings file comments
    CfgFileHeader,
    CfgConfigVersion,
    CfgApplicationSection,
    CfgStartMinimizedToTray,
    CfgMinimizeToTray,
    CfgCloseButtonAction,
    CfgShowConsole,
    CfgSingleInstance,
    CfgStartWithWindows,
    CfgLanguage,
    CfgTraySection,
    CfgTrayEnabled,
    CfgTrayTooltip,
    CfgNotificationsSection,
    CfgNotifyOnError,
    CfgNotifyOnDeviceChange,
    CfgNotifyOnStateChange,
    CfgMenuSection,
    CfgMenuShowStatus,
    CfgMenuToggle,
    CfgMenuReinitialize,
    CfgMenuSettings,
    CfgMenuLog,
    CfgMenuDiagnostics,
    CfgMenuStartWithWindows,
    CfgMenuAbout,
    CfgMenuExit,
    CfgAudioSection,
    CfgEnabledOnStartup,
    CfgDataFlow,
    CfgRole,
    CfgPeriodSelection,
    CfgRequestedPeriodFrames,
    CfgAllowPeriodSnap,
    CfgReleaseOnExit,
    CfgReinitSection,
    CfgReinitDeviceChanged,
    CfgReinitDeviceState,
    CfgReinitDeviceAdded,
    CfgReinitDeviceRemoved,
    CfgReinitResume,
    CfgReinitUnlock,
    CfgReinitEnableWhenDisabled,
    CfgReinitFailureTimeout,
    CfgReinitDebounce,
    CfgPerformanceSection,
    CfgProcessPriority,
    CfgDisablePowerThrottling,
    CfgUpdatesSection,
    CfgUpdatesMode,
    CfgUpdatesRepository,
    CfgUpdatesCheckOnStartup,
    CfgHotkeysSection,
    CfgHotkeysEnabled,
    CfgHotkeysToggle,
    CfgHotkeysReinitialize,
    CfgLoggingSection,
    CfgLoggingLevel,
    CfgLoggingToConsole,
    CfgLoggingToFile,
    CfgLoggingFilePath,
    CfgLoggingMaxFileSize,
    CfgLoggingMaxFiles,

    Count,
};

// Language of the current session. "auto" means the language of Windows.
Language Detect();
Language FromCode(const std::string& code);
const char* Code(Language language);

void Set(Language language);
Language Current();

// Text in the current language.
const char* Utf8(Str id);
std::wstring Wide(Str id);

}
