#pragma once

#include <string>

namespace miniant::Lang {

enum class Language {
    English,
    Russian,
};

// Every string that the application shows to the user, writes to the log or
// puts into the settings file as a comment.
//
// Keep this list and the table in Lang.cpp in sync: every identifier must have
// an English and a Russian text.
enum class Str {
    // Main window
    WindowTitle,
    StatusStarting,
    ButtonReinitialize,
    ButtonFileMenu,
    ButtonOptions,
    ButtonOpenLog,
    ButtonDiagnostics,
    ButtonAbout,
    ButtonExit,

    // Tray menu
    TrayToggleEnabled,
    TrayReinitialize,
    TrayLog,
    TrayDiagnostics,
    TrayStartWithWindows,
    TrayAbout,
    TrayExit,

    // Status line
    StatusDisabled,
    StatusNotActive,
    StatusDriverMinimum,
    StatusPeriodLocked,
    StatusMoreDevices,

    // Notifications (short on purpose: a balloon shows only a few words)
    NotifyTitle,
    NotifyAudioTitle,
    NotifyDeviceTitle,
    NotifyDeviceNotReady,
    NotifyDeviceNotReadyHelp,
    NotifyDisabledNoDevice,
    NotifyEnabled,
    NotifyDisabled,
    NotifyDeviceChanged,
    NotifyUpdateAvailable,
    NotifyUpdateLatest,
    NotifyUpdateFailed,
    NotifyUpdateClick,
    NotifyReportFailed,

    StatusSuspended,
    StatusActive,
    UnknownDevice,
    FlowRender,
    FlowCapture,
    LogMutexFailed,
    LogInstanceNoAnswer,
    LogSettingsUnreadable,
    LogComFailed,
    LogWindowFailed,
    LogSessionNotifications,
    LogTrayHidden,
    LogPriorityFailed,
    LogPowerThrottlingFailed,
    LogPowerThrottlingOff,
    LogPowerThrottlingUnavailable,
    LogSettingsWriteFailed,
    RestartNeededTitle,
    RestartNeededText,
    RestartNeededHint,
    RestartLaterHint,
    ErrRestartFailed,
    OpRestarting,
    LogLanguageChanged,
    LogFileOff,
    LogFileMissing,
    LogLogSnapshotFailed,
    LogUpdatesDisabled,
    LogUpdateRunning,
    LogReinitInvalid,
    LogApplyRetry,
    LogResumeApply,
    LogHotkeyRegisterFailed,
    LogHotkeyParseFailed,
    LogAutostartOpenFailed,
    LogAutostartWriteFailed,
    LogUpdateLeftover,
    LogStopped,
    LogRepeated,
    LogLowLatencyStarted,
    LogPeriodLocked,
    LogDiagCollected,
    LogDiagEnumeratorReady,
    LogDiagEnumeratorMissing,
    LogDiagEndpoints,
    LogDiagReportBuilt,
    LogTrayCreateFailed,
    LogTrayConfigureFailed,
    LogWindowClassFailed,
    LogWindowCreateFailed,

    ErrAudioEnumeratorFailed,
    ErrAudioNotificationsFailed,
    ErrNotInitialised,
    ErrLowLatency,
    ErrNoEndpoint,
    ErrStreamInvalid,
    ErrDefaultEndpointQuery,
    ErrDefaultDeviceChanged,
    ErrStreamNotRunning,
    ErrOpenEndpoint,
    ErrEndpointTransient,
    ErrNoAudioClient3,
    ErrActivateClient,
    ErrMixFormat,
    ErrEnginePeriods,
    ErrEngineLocked,
    ErrInitStream,
    ErrStartStream,
    ErrUrlParse,
    ErrResponseTooLarge,

    ReasonResume,
    ReasonUnlock,
    ConsoleReportWritten,
    ArgConfigNeedsPath,
    ArgLogLevelNeedsValue,
    ErrEmptyUrl,
    ErrNoUpdateRepository,
    ErrGithubUnreachable,
    ErrNoReleases,
    ErrRateLimit,
    ErrHttpStatus,
    ErrGithubParse,
    ErrGithubUnexpected,
    ErrNoReleaseVersion,
    ErrDeleteLeftover,
    DiagTitle,
    DiagRule,
    DiagVersion,
    DiagGenerated,
    DiagWindows,
    DiagExecutable,
    DiagSettings,
    DiagConfig,
    DiagEnumeratorError,
    DiagAudiosrvHint,
    DiagDevicesRender,
    DiagDevicesCapture,
    DiagNoDevices,
    DiagDefaultMark,
    DiagCommunicationMark,
    DiagDeviceId,
    DiagDriver,
    DiagFormat,
    DiagPeriods,
    DiagUnknown,
    DiagResult,
    DiagSmallBuffer,
    DiagNoGain,
    DiagNoAudioClient3,
    DiagNotesHeader,
    DiagNotes,
    DiagPeriodsNoClient3,
    DiagPeriodDefault,
    DiagPeriodMinimum,
    DiagPeriodFundamental,
    DiagPeriodMaximum,
    DiagNoAudioClient3Detail,
    DiagMixFormatFailed,
    DiagEnginePeriodsFailed,
    DiagActivateFailed,

    SettingsPrefix,

    // Command line help (one block per language)
    HelpText,

    // Dialogs
    AboutTitle,
    AboutText,
    AboutUsage,
    AboutConfig,
    AboutProject,
    AboutSettings,
    DiagnosticsWriteFailed,

    // Console / log: operations
    OpStarted,
    OpSettingsFile,
    OpSettingsCreated,
    OpSettingsReloaded,
    OpCommentsRewritten,
    OpSettingsUpgraded,
    OpAlreadyRunning,
    OpApplied,
    OpLogOpened,
    OpDriverMinimum,
    OpApplyFailed,
    OpEnabled,
    OpDisabled,
    OpDeviceChanged,
    OpDeviceNotReady,
    OpGaveUp,
    OpDiagnostics,
    OpDiagnosticsFailed,
    OpHotkeys,
    OpAutostart,
    OpUpdateChecking,
    OpExiting,
    OpTrayUnavailable,
    OpSessionNotificationFailed,
    OpDiagHint,
    ValueOn,
    ValueOff,

    SettingsWindowTitle,
    SettingsSave,
    SettingsCancel,
    SettingsOpenFile,
    SettingsInvalidValues,
    SettingsOpenFileFailed,
    SettingsTabWindow,
    SettingsTabAudio,
    SettingsTabOther,
    SettingsHeaderApplication,
    SettingsHeaderTray,
    SettingsHeaderMenu,
    SettingsHeaderAudio,
    SettingsHeaderReinit,
    SettingsHeaderPerformance,
    SettingsHeaderHotkeys,
    SettingsHeaderUpdates,
    SettingsHeaderLog,
    SettingsLanguage,
    SettingsLanguageAuto,
    SettingsLanguageEnglish,
    SettingsLanguageRussian,
    SettingsStartWithWindows,
    SettingsStartMinimized,
    SettingsMinimizeToTray,
    SettingsCloseAction,
    SettingsCloseMinimize,
    SettingsCloseExit,
    SettingsSingleInstance,
    SettingsTrayEnabled,
    SettingsTrayTooltip,
    SettingsNotifyError,
    SettingsNotifyDeviceChange,
    SettingsNotifyStateChange,
    SettingsMenuStatus,
    SettingsEnabledOnStartup,
    SettingsDataFlow,
    SettingsFlowRender,
    SettingsFlowCapture,
    SettingsFlowBoth,
    SettingsPeriod,
    SettingsPeriodMinimum,
    SettingsPeriodFundamental,
    SettingsPeriodFixed,
    SettingsRequestedPeriod,
    SettingsAllowPeriodSnap,
    SettingsReinitDeviceChanged,
    SettingsReinitDeviceState,
    SettingsReinitDeviceAdded,
    SettingsReinitDeviceRemoved,
    SettingsReinitResume,
    SettingsReinitUnlock,
    SettingsReinitEnableWhenDisabled,
    SettingsReinitFailureTimeout,
    SettingsReinitDebounce,
    SettingsProcessPriority,
    SettingsPriorityNormal,
    SettingsPriorityBelowNormal,
    SettingsPriorityIdle,
    SettingsDisablePowerThrottling,
    SettingsHotkeysEnabled,
    SettingsHotkeyToggle,
    SettingsHotkeyReinitialize,
    SettingsCheckOnStartup,
    SettingsLogLevel,
    SettingsLogFilePath,
    SettingsLogMaxFileSize,
    SettingsLogMaxFiles,

    // Settings file comments
    CfgFileHeader,
    CfgApplicationSection,
    CfgStartMinimizedToTray,
    CfgMinimizeToTray,
    CfgCloseButtonAction,
    CfgSingleInstance,
    CfgStartWithWindows,
    CfgLanguage,
    CfgTraySection,
    CfgTrayEnabled,
    CfgTrayTooltip,
    CfgNotificationsSection,
    CfgNotifyOnError,
    CfgNotifyOnDeviceChange,
    CfgNotifyOnStateChange,
    CfgMenuSection,
    CfgMenuShowStatus,
    CfgMenuToggle,
    CfgMenuReinitialize,
    CfgMenuLog,
    CfgMenuDiagnostics,
    CfgMenuStartWithWindows,
    CfgMenuAbout,
    CfgMenuExit,
    CfgAudioSection,
    CfgEnabledOnStartup,
    CfgDataFlow,
    CfgPeriodSelection,
    CfgRequestedPeriodFrames,
    CfgAllowPeriodSnap,
    CfgReinitSection,
    CfgReinitDeviceChanged,
    CfgReinitDeviceState,
    CfgReinitDeviceAdded,
    CfgReinitDeviceRemoved,
    CfgReinitResume,
    CfgReinitUnlock,
    CfgReinitEnableWhenDisabled,
    CfgReinitFailureTimeout,
    CfgReinitDebounce,
    CfgPerformanceSection,
    CfgProcessPriority,
    CfgDisablePowerThrottling,
    CfgUpdatesSection,
    CfgUpdatesCheckOnStartup,
    CfgHotkeysSection,
    CfgHotkeysEnabled,
    CfgHotkeysToggle,
    CfgHotkeysReinitialize,
    CfgLoggingSection,
    CfgLoggingLevel,
    CfgLoggingFilePath,
    CfgLoggingMaxFileSize,
    CfgLoggingMaxFiles,

    Count,
};

// Language of the current session. "auto" means the language of Windows.
Language Detect();
Language FromCode(const std::string& code);
const char* Code(Language language);

void Set(Language language);
Language Current();

// Text in the current language.
const char* Utf8(Str id);
std::wstring Wide(Str id);

}
